name: CI
on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  repository-projects: read
    
jobs:
  solidity-base:
    uses: init4tech/actions/.github/workflows/solidity-base.yml@main
    with:
      gas-diff-tolerance: 2 # setting the gas diff tolerance to 2%
